services:
  - type: web
    name: kucoin-bot
    env: python
    plan: free
    buildCommand: pip install -r src/requirements.txt
    startCommand: python src/main.py
    autoDeploy: true
    envVars:
      TELEGRAM_TOKEN:
        sync: false
