services:
  - type: web
    name: kucoin-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python coinbot.py
    autoDeploy: true
    envVars:
      TELEGRAM_TOKEN:
        sync: false
